test Pipe 3

diff --git a/.github/workflows/pushAPI.yml b/.github/workflows/pushAPI.yml
--- a/.github/workflows/pushAPI.yml
+++ b/.github/workflows/pushAPI.yml
@@ -68,8 +68,10 @@ jobs:
           java-version: '21'
           distribution: 'temurin'
           cache: maven
+      - name: Verify POM file
+        run: test -f restAPI/pom.xml || { echo "POM file missing in restAPI"; exit 1; }
       - name: Build with Maven
-        run: mvn -B package --file pom.xml
+        run: mvn -B package --file restAPI/pom.xml
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
       - name: Update dependency graph
